rn_npv/npv/urls.py
from django.urls import path

from . import views


app_name = 'rn'

urlpatterns = [
    path('', views.index, name='npv'),
]

rn_npv/rn_npv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('npv.urls', namespace="rn"))
]

rn_npv/npv/models.py
from django.db import models


class ResultModel(models.Model):
    npv_result = models.FloatField()

rn_npv/npv/forms.py
from django import forms


class NpvForm(forms.Form):
    year = forms.IntegerField(min_value=2020, max_value=2050)
    k = forms.FloatField()

rn_npv/npv/views.py
from django.shortcuts import render, redirect

from .forms import NpvForm

from .models import ResultModel


def calc_npv(k, year, start_year=2020):
    '''Расчет NPV на каждый год'''
    n = year - start_year
    # в списке income вносим данные чистого денежного дохода по годам 2020-2050 соответственно
    income = [1000, 1000, 500, 500, 1000, 1000,
              1000, 1000, 1000, 1000, 1000, 1000, 1000,
              1000, 1000, 1000, 1000, 1000, 1000, 1000,
              1000, 1000, 1000, 1000, 1000, 1000, 1000,
              1000, 1000, 1000, 1000]

    if n == 0:
        return round((income[n]/(1+k)**(n+1)), 2)
    return round((income[n]/(1+k)**(n+1) + calc_npv(k, year-1)), 2)


def index(request):
    '''Считываем данные'''
    last_npv = ResultModel.objects.last()
    if request.method == 'POST':
        form = NpvForm(request.POST)
        if form.is_valid():
            year = form.cleaned_data['year']
            k = form.cleaned_data['k']
            npv = calc_npv(k, year)
            npv_new = ResultModel(npv_result=npv)
            npv_new.save()
        return redirect('rn:npv')
    else:
        context = {
            'last_npv': last_npv,
        }
        return render(request, 'homepage.html', context=context)

rn_npv/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Страница расчета</title>
  </head>
  <body>
    <form method="post" action="{% url 'rn:npv' %}">
      {% csrf_token %}
      <table>
        <tr>
          <th><label for="id_year">Год:</label></th>
          <td>
            <input id="id_year" name="year" type="integer" value="2050" required />
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th><label for="id_k">Коэффициент:</label></th>
          <td>
            <input id="id_k" name="k" type="float" value="0.2" required />
          </td>
        </tr>
      </table>
      <button type="submit" class="btn btn-primary">Расчет</button>
    </form>
    Результат:

    <h1>
      {{ last_npv.npv_result }}
    </h1>

  </body>
</html>